### ISSUE TITLE
Make a loseLife() function?

### ISSUE THREAD

**Issue by christhomas** [yakotta/smack-a-dot#1]
https://github.com/yakotta/smack-a-dot/blob/9527db386748d26095257158a1b8dcf8e40234b4/script.js#L63

You lose a life when you click the wrong thing, or run out of time, instead of repeating the same code in both places, why not call a function which does the same thing, its a small issue, but its more about the idea, than the number of lines, its bad to repeat yourself unnecessarily.

However, too much refactoring is also a bad idea, it can create unnecessary complexity too, so its a balance between doing the right thing and making your code hard to read.

However in this case, I think you should put a loseLife() function and use it here and in the death timer

**Comment by yakotta** [comment]
It was technically one code, "UI.update(deltapoints, deltalives)" would handle both lost lives and won points. But I've separated them into "lostLife()" and "winPoint()" to make the code a bit easier to read.
