### ISSUE TITLE
Create a winPoint function

### ISSUE THREAD

**Issue by christhomas** [yakotta/smack-a-dot#2]
https://github.com/yakotta/smack-a-dot/blob/9527db386748d26095257158a1b8dcf8e40234b4/script.js#L66

just for consistency, perhaps if you're going to add a function for loseLife() you should have a function for winPoint, then your game logic is consistently held in functions, you only need to do this, if you're going to do the loseLife() function, cause they only make sense to do both, or none of them

**Comment by yakotta** [comment]
same as loseLife() issue
