### ISSUE TITLE
Put this code which hides dots, into the revealDot function

### ISSUE THREAD

**Issue by christhomas** [yakotta/smack-a-dot#3]
https://github.com/yakotta/smack-a-dot/blob/9527db386748d26095257158a1b8dcf8e40234b4/script.js#L91

Perhaps revealDot should be called "selectDot" instead? and then we can justify putting this line which hides all the dots into the function as well and then we keep our code which adjusts which dot is visible all in the same place?

Cause now we have half the task to hide the dots in one place and another half of the task to reveal a single dot in another place, better to have it all in the same place, then its easier to read, right?

**Comment by yakotta** [comment]
Makes sense. Done.
