### ISSUE TITLE
You only need to use .php as a file extension when you're project incorporates php

### ISSUE THREAD

**Issue by christhomas** [yakotta/smack-a-dot#4]
I've noticed here that you're naming your html files things like index.php when there is no php in the entire project. It should be index.html

As a general rule, you should follow this guideline:
1. If ONE or MORE files in your project incorporates php code, then ALL your html files must be named with a .php extension. This is for consistency reasons. file1.php, file2.php, file3.html is weird. It doesn't match and isn't consistent.
2. if ZERO of your files have php inside them. Then ALL your html files must end with .html

There is a good technical reason for this. Sometimes you build a static website, which this project is. And you want to host it on a platform which won't recognise .php files because they are php scripts and it doesn't support them. In this scenario, your project won't run.

Also, because this is a html/javascript project, there is no need to use .php as a file extension since you are only working with html and javascript.

Do you mind changing it?

**Comment by yakotta** [comment]
fixed.
